apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: deliver-order-service
  name: deliver-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: deliver-order-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-collector: "true"
        io.kompose.network/docker-deliver-order-db: "true"
        io.kompose.network/docker-redis-network: "true"
        io.kompose.service: deliver-order-service
    spec:
      containers:
        - env:
            - name: BACKEND_DB_IP
              value: deliver-order-db
            - name: BACKEND_DB_NAME
              value: deliver-order
            - name: BACKEND_DB_PASSWORD
              value: password
            - name: BACKEND_DB_PORT
              value: "5432"
            - name: BACKEND_DB_USERNAME
              value: postgres
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/scalable-23t1-p4-we-sell-late-tokens/deliver-order-service/scalable-p4-deliver-order:latest
          name: deliver-order-service
          ports:
            - containerPort: 8080
              hostPort: 8083
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
