apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-collector: "true"
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file=/etc/tempo.yml
          image: grafana/tempo:latest
          name: tempo
          ports:
            - containerPort: 3200
              hostPort: 3200
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/tempo.yml
              name: tempo-claim0
      restartPolicy: Always
      volumes:
        - name: tempo-claim0
          persistentVolumeClaim:
            claimName: tempo-claim0
status: {}
